//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoCalendario.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Carrera
    {
        public int id_carrera { get; set; }
        public string carrera1 { get; set; }
        public Nullable<int> fk_sede { get; set; }
    }
}
