//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoCalendario.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reserva
    {
        public int id_reserva { get; set; }
        public Nullable<int> fk_gimnasio { get; set; }
        public Nullable<int> fk_usuario { get; set; }
        public Nullable<int> fk_hora { get; set; }
        public Nullable<System.DateTime> fecha { get; set; }
    
        public virtual Hora Hora { get; set; }
        public virtual Usuarios Usuarios { get; set; }
    }
}
